controller_list:
  - name: fake_robot_arm_hand_controller
    type: $(arg fake_execution_type)
    joints:
      - joint1
      - joint2
      - joint3
      - gripper_joint
initial:  # Define initial robot poses per group
  - group: robot_arm_hand
    pose: home